project_id = "Tsuyo"

[auth]
site_url = "https://tsuyo.vercel.app"
additional_redirect_urls = ["https://tsuyo.vercel.app/account", "https://tsuyo.vercel.app/account?mode=recovery", "http://localhost:5173/account", "http://localhost:5173/account?mode=recovery", "http://192.168.0.16:5173/account", "http://192.168.0.16:5173/account?mode=recovery"]

[functions.store-api]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.store-jobs]
verify_jwt = false
